const express = require("express");
const adminDB = require("../db/adminDB");

const usersRoutes = express.Router();

usersRoutes.post("/new-user", (req, res) => {
  const body = req.body;
  let date = new Date().toLocaleDateString("fa-IR");

  let newUser = `INSERT INTO users VALUES (NULL,"${body.firstname}","${body.lastname}","${body.username}","${body.password}","${date}")`;

  adminDB.query(newUser, (err, result) => {
    if (err) {
      console.log(err);
      return res.status(422).json({ message: "user not valid" });
    }

    console.log("user added");

    res.json({
      id: result.insertId, // ID generated by MySQL
      firstname: body.firstname,
      lastname: body.lastname,
      username: body.username,
      password: body.password,
      date: date,
    });
  });
});

usersRoutes.get("/all-users", (req, res) => {
  let getAllUsersQuery = `SELECT * FROM users`;

  adminDB.query(getAllUsersQuery, (err, result) => {
    if (err) {
      console.log(err);
      return res
        .status(422)
        .json({ message: "there is no user in your database!" });
    } else {
      console.log("all users", result);
      res.send(JSON.stringify(result));
    }
  });
});

usersRoutes.delete("/remove/:userID", (req, res) => {
  let userID = req.params.userID;

  let deleteUserQuery = `DELETE FROM users WHERE id = ${userID}`;

  adminDB.query(deleteUserQuery, (err, result) => {
    if (err) {
      console.log(err);
      res.json({ message: "there is no user with this id in your database!" });
    } else {
      console.log("user deleted: ", result);
      res.json({
        message: "user deleted successfully!",
      });
    }
  });
});

usersRoutes.put("/edit/:userID", (req, res) => {
  let userID = req.params.userID;
  let body = req.body

  let updateUserQuery = `UPDATE users SET firstname="${body.firstname}",lastname="${body.lastname}",username="${body.username}",password="${body.password}" WHERE id = ${userID}`;

  adminDB.query(updateUserQuery, (err, result) => {
    if (err) {
      console.log(err);
      res.json({ message: "there is no user with this id in your database!" });
    } else {
      console.log("user updeted: ", result);
      res.send(JSON.stringify(result));
    }
  });
});

module.exports = usersRoutes;
